### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Lexcorp3439/VKmessenger#1]
0. У меня так и не получилось запустить ваше приложение на эмуляторе. Пробовал образы `Nexus 5X API P (x86)` и `Nexus 5X API 27 (x86)`. Приложение просто завершается, ничего внятного в лог не написав.
1. Приведите в порядок Code Style он у вас неконсистентен даже в рамках приложения.
2. https://github.com/Lexcorp3439/VKmessenger/blob/e9626616492d003cc25e0dd5a0814c7be170bc08/app/src/main/java/com/example/admin/vkmess/AutenWeb.java#L57-L58
За такое в приличном обществе бьют. Разберитесь пожалуйста, как средствами стандартной Джавы или Андроида парсить URL. Формирование URL через конкатенацию выглядит чуть менее страшно, но лучше тоже воспользоваться библиотечным решением.
3. Уберите `System.out.println` где не нужно и замените на андроидовский механизм логгинга там, где нужно.
4. Непонятно, зачем в классе `Application` вы инициализируете `VkSdk`, хотя для взимодейтсвия с VK вы используете свой код
5. Вместо Джавовского потока с `BlockingQueue` скорее всего можно использовать андроидовские средства для асинхронных задач: https://developer.android.com/reference/android/os/Handler или тот же AsyncTask, который вы уже используете.
6. Вместо хранения состояния в глобальных переменных наверняка тоже можно испоьзовать андроидовские средства. Более того, можно сохранить настройки между запусками. 
7. Более правильный способ реализовать OAuth 2.0 на андроиде: открыть /authorize в системном браузере, `redirect_uri` поставить на url, который обрабатывает ваше приложение (например: `vkmess://oauth_callback`). Обработку URL можно добавить через intent filter: https://developer.android.com/guide/components/intents-filters
8. Поля класса в Джаве не принято делать публичными почти никогда. Так вы их делаете частью API класса и если вы захотите их убрать или заменить, то вам придётся переписывать весь код, использующий этот класс. Усугубляет проблему то, что у кучи ваших полей тип `ArrayList` (хотя можно использовать интерфейс). Если не нравится писать везде геттеры и сеттеры, то пишите, например, на Котлине, там эта проблема решена.

Это пока всё, что удалось увидеть с учётом того, что я не смог запустить приложение.

**Comment by Lexcorp3439** [comment]
0. ? Я чуть подправил программу в месте, из-за чего возможно у вас не запускалась, но мы вчера с Кириллом попробовали, и у него все работает(((
1. +-Я вроде подправил что нашел
2. +- Стало лучше, но все равно мне не оч нравится(((
3. +Все вроде исправил
4. +Этот класс я просто забыл убрать, уже удалил его 
5. +Использовал для всех запросов AsyncTask
6. +-Я сделал так, чтоб не было глобальных переменных id и token, теперь они хранятся приватно только в VKLib, а другие классы не имеют доступ за ненадобностью. Я думаю, что такое решение тоже сойдет)
7. -Пока не особо понимаю как переделать то, что написано в 7 пункте, буду над этим работать...
8. +Использовал getter, теперь все по фен-шуй

**Comment by gagarski** [comment]
1. Баг с неизвестным человеком в списке сообщений всё ещё остался. Попробуйте подебажить/пологировать ответы от API

2. С загрузкой аватарок тоже есть баги: 
<img src="https://imgur.com/fhPt0xX.png"/>
Такое ощущение, что вы ожидаете, что ответы придут в том же порядке, что и запросы, а это не так (или я ошибаюсь, тут не вникал). Ещё аватарки было бы хорошо кешировать. 

3. В панели, которая вытаскивается сбоку показывается не моё имя и есть явно лишние пункты в меню.

4. По поводу #6. У некоторых сервисов в пользовательском соглашении предполагается, что OAuth-диалог для аутентификации вы будете показывать в стандартном браузере. В коллбэк вы ставите URL, который обрабатывает ваше приложение (регистрируется с помощью механизма intent filters). Из коллбэка вы завершаете аутентификацию. В принципе использование стандартного браузера довольно логично: конечному пользователю легче понять, не занимаетесь ли вы фишингом с помощью своего приложения, но если это останется за рамками курсача, то я переживу.

**Comment by gagarski** [comment]
> С загрузкой аватарок тоже есть баги

Судя по всему, по этому поводу в классе `DownloadImage` было предупреждение, которое вы засапрессили.

> Баг с неизвестным человеком в списке сообщений всё ещё остался

Неизвестный человек получается из известного путём откидывания одной цифры от ID.

**Comment by Lexcorp3439** [comment]
Все сделано!!!
